{% set name = "PyMinHash" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyMinHash-{{ version }}.tar.gz
  sha256: 16a9ab842811c6c53d9153ef402e401b853e55808f267f769d2154117e6ec94f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - openpyxl
    - pandas
    - pytest
    - scikit-learn

test:
  imports:
    - pyminhash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fritshermans/pyminhash
  summary: Efficient MinHashing
  license: MIT
  license_file: LICENSE
  description: |
    MinHashing is a very efficient way of finding similar records in a dataset based on Jaccard similarity. PyMinHash
    implements efficient minhashing for Pandas dataframes. See instructions below or look at the example notebook to get
    started.

    Developed by [Frits Hermans](https://www.linkedin.com/in/frits-hermans-data-scientist/)

    PyPI: [https://pypi.org/project/PyMinHash/](https://pypi.org/project/PyMinHash/)

  doc_url: https://pyminhash.readthedocs.io/en/latest/
  dev_url: https://github.com/fritshermans/pyminhash

extra:
  recipe-maintainers:
    - sugatoray
